-- Create database and use the database with \c
-- Create tables:
    -- Create departments - create department schema and the seeds first
    -- Create roles
    -- Create employees - will reference the roles table and will have foreign keys for it's own table employees and for another employee row for the managers
-- Work next on the seeds.sql to create departments, roles, and then employees in the order we did above